power <- subset(read.table(file = "household_power_consumption.txt", header = TRUE, sep = ";"), Date == "1/2/2007" | Date == "2/2/2007")
power <- cbind(power[3:9], strptime(paste(power$Date, power$Time, sep = " "), format = "%d/%m/%Y %H:%M:%S"))
colnames(power) <- c(names(power)[1:7], "Date_and_Time")

png("plot3.png", 480, 480)
with(power, plot(Date_and_Time, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering"), yaxt = "n")
axis(2, at = c(0,10,20,30), lab = c("0", "10", "20", "30"))
lines(power$Date_and_Time, power$Sub_metering_2, type = "l", col = "red")
lines(power$Date_and_Time, power$Sub_metering_3, type = "l", col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = c(1,1,1))
dev.off()